navbar:
  blog_title: 铃溪的blogs
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/picture177.jpg
  banner_img_height: 100
  slogan:
    text: Hi! This is LingXi's blogs
post:
  banner_img: /images/uploads/mmexport1602581319886.webp
  banner_img_height: 70
  default_index_img: /images/uploads/picture122.jpg
archive:
  banner_img: /images/uploads/picture139.png
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/picture001.png
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/picture001.png
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/picture019.jpg
  banner_img_height: 80
  subtitle: null
  avatar: /img/avatar.png
  name: 铃溪的blogs
  intro: 探寻天地之理，以窥宇宙之秘
links:
  banner_img: /images/uploads/picture064.png
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: 暮雨千泷
      intro: 青天白日梦神仙
      link: https://www.myql.xyz
      avatar: https://cdn.jsdelivr.net/gh/leicancun/img@main/images/avatar.webp
